sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- curl -L -o master.zip https://github.com/akeep/nanopass-framework-racket/archive/master.zip
- unzip master.zip
- raco pkg install -n nanopass nanopass-framework-racket-master/

script:
- racket tests/test-all.rkt
- echo "done"

after_script:
